### ISSUE TITLE
Write a chapter on What is an IT culture?

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/open-org-it-culture#11]
1,000-1,500 words, due April 7

**Comment by GIANTCRAB** [comment]
Hi! Is anyone working on this? I would love to help work on this chapter.

**Comment by semioticrobotic** [comment]
Hey, @GIANTCRAB! Yes, Jono Bacon has agreed to write this chapter (we're just waiting for him to accept our GitHub invitation so we can properly tag him on it). But I bet he'd be open to any input you might have! And if there's a different angle on culture you might like to pursue, we can chat about that, too. You can post it in the general "brainstorming" issue, where we're collecting those things!

**Comment by GIANTCRAB** [comment]
@semioticrobotic which articles are available for work?

**Comment by semioticrobotic** [comment]
Well, @GIANTCRAB, all the topics/chapters that we initially identified as desirable are claimed and underway; however, we are _very_ open to hearing ideas and pitches on alternatives and additions (see @LauraHilliger in #18, for example). Please help us see angles and topics (with an IT focus, of course) we hadn't considered before!

**Comment by jhibbets** [comment]
Assigned to @jonobacon

**Comment by semioticrobotic** [comment]
Chapter is complete and now in production via galley proofs.
