### ISSUE TITLE
Write a chapter on Hiring with culture in mind

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/open-org-it-culture#12]

**Comment by semioticrobotic** [comment]
How are things going, @juliegund? Can I help you in any way as you finish up your draft?

**Comment by juliegund** [comment]
Hi Bryan I apologize, I got sick and then have been traveling. You will have the finished copy eob Monday if that still works.

Julie Gunderson
Community and Relationship Manager

**Comment by semioticrobotic** [comment]
You bet, @juliegund. Looking forward to it. Glad to hear you're feeling better!

**Comment by semioticrobotic** [comment]
Sorry that we couldn't land this in time for the deadline, @juliegund. But please know that we're still interested in publishing the article on Opensource.com, should you be interested in submitting it!

**Comment by juliegund** [comment]
Bryan I am so sorry – my son ended up very ill – to the point of Emergency room and I missed everything I was supposed to be doing

Julie Gunderson
Community and Relationship Manager

**Comment by semioticrobotic** [comment]
I'm so sorry to hear this new, @juliegund, and I hope your son is doing well now. We can always revisit this at a later date for another project.
