### ISSUE TITLE
Write a chapter on Leveraging the power of impact mapping

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/open-org-it-culture#13]

**Comment by jhibbets** [comment]
Got a lead that we should pursue Goiko Adzic (the author of the book on impact mapping) for this opportunity. Does anyone know Goiko and can introduce us?

**Comment by semioticrobotic** [comment]
Reached out [on Twitter](https://twitter.com/openorgbook/status/845048174771359744), and will follow-up where I can. Thanks for the tip!

**Comment by sherl0cks** [comment]
Im in and will take this. I've been practicing for 5 years now. Email sent separately

**Comment by semioticrobotic** [comment]
Very glad to hear that, @sherl0cks! We're thrilled. Thanks for reaching out. I'll look for your email.

**Comment by semioticrobotic** [comment]
@sherl0cks did a fantastic job. Look for the chapter in the page proofs soon.
