### ISSUE TITLE
Write an introduction to the book

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/open-org-it-culture#14]
We have sent a request to Gene Kim to write this.

**Comment by jimmysjolund** [comment]
What kind of help is needed?

**Comment by semioticrobotic** [comment]
We're still in need of someone to write this, but, as @jhibbets indicates above, we've aimed high and asked Gene Kim to do it. Nevertheless, it's marked as "help wanted" until such time as we _officially_ have someone signed up to do it.

**Comment by jhibbets** [comment]
We have Mike Kelly, Red Hat CIO signed up for this. I am meeting with him on May 2 to go over the project and get him brought up to speed.

**Comment by semioticrobotic** [comment]
Mike and I are working on the introduction this week—more soon.

**Comment by semioticrobotic** [comment]
Mike Kelly's introduction is now typeset and available in the book's galley proofs.
