### ISSUE TITLE
Write the introduction to Part 2: Practices

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/open-org-it-culture#17]

**Comment by semioticrobotic** [comment]
How are things going, @jyee? Can I be of any help as you work on your draft?

**Comment by jyee** [comment]
@semioticrobotic Sorry, was waiting on some draft chapters to provide better references for the intro, but then lost track of time. I'm back on it and will have a draft ready this Saturday.

**Comment by semioticrobotic** [comment]
Perfectly understandable, @jyee! Be sure to check out the page proofs in the repo; I think the currently typeset chapters should provide good grist for the mill.

**Comment by semioticrobotic** [comment]
How's it going @jyee? Need anything from us?

By the way, the table of contents for the section you're introducing is now set, and most of the chapters have been typeset (just in case you wanted to reference them when finishing your introduction).

**Comment by semioticrobotic** [comment]
Just checking in once more, @jyee. Do you think we can wrap up this introduction by the end of the calendar week?

**Comment by jhibbets** [comment]
I talked with @jyee last night. He gave a pretty cool Ignite talk btw. He's
at OSCON this week and was waiting on the final chapter listings to make
sure he didn't talk about something that wasn't mentioned. Without speaking
for him, I seem to recall that he was going to try to knock this out early
next week.

**Comment by jyee** [comment]
Sorry, I've been out of touch. Yes, I'm planning to have this done by this
coming weekend.

**Comment by semioticrobotic** [comment]
Perfect. Thanks, @jyee. (Any video of the aforementioned "cool talk," by the way?)

**Comment by semioticrobotic** [comment]
Fantastic introduction from @jyee is now available for review in the daily page proofs.
