### ISSUE TITLE
Write a chapter on blameless cultures

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-it-culture#2]
We'll need to compose a chapter on "blameless postmortems."

(See the [current table of contents](https://github.com/open-organization-ambassadors/open-org-it-culture/blob/master/open_org_it_culture_toc.md).)

**Comment by jhibbets** [comment]
@mindweather Heard that you might be a good person to help us with this. I've been waiting on an introduction from John Willis to connect us with you. While I was talking with John at SCALE 15x (Southern California Linux Expo) during their DevOps day, he suggested that you would be perfect for this. What's the best way to connect?

**Comment by jhibbets** [comment]
Very excited to have you onboard @mindweather can't wait to read your chapter.

**Comment by semioticrobotic** [comment]
With much regret, @mindweather has declined to compose this chapter of the book. Anyone with something relevant already composed should feel free to pitch it before May 1; otherwise, we'll proceed without this particular chapter of the book.

**Comment by semioticrobotic** [comment]
Looks like we won't get this one after all, so I'm closing this issue as we're now under content freeze.
