### ISSUE TITLE
Additional chapters: Failing fast / Spanning boundaries / Productive debate

### ISSUE THREAD

**Issue by ruhbehka** [open-organization-ambassadors/open-org-it-culture#22]
Hi,
I'd like to propose two additional chapters:

For "New Skills" - One by DeLisa Alexander, either:
- "Failing fast: Learning to release early and often" -- adapted from this article to include some new tips and tricks: https://opensource.com/business/10/7/fear-failure-embrace-it-failing-fast
OR
- "Working across organizational boundaries" -- adapted from this article, again with some new material: https://opensource.com/business/10/6/let-open-source-way-take-you-outside-your-comfort-zone

For "New culture" - one by me, adapted from this article, maybe with a focus on how to foster productive debate, e.g. "The role of productive debate in an open organization"?
https://opensource.com/open-organization/17/1/force-for-good-community

**Comment by semioticrobotic** [comment]
Two solid proposals, @ruhbehka. Thanks for offering them.

The piece on "failing fast" is a bit too redundant with chapters already accepted into the volume (and currently in draft state), so I believe the second, on "comfort zones," might be a better fit. I'd like to hear more about the IT-specific angle DeLisa would be taking on that one.

We currently don't have anything on "productive debate" or "constructive dissent," and would welcome that. You and I can work together to tailor what you've already published in that regard (for example, we already have a chapter on "assuming positive intent," so I'd recommend excising that bit), and find the best IT-appropriate angle on it.

The trick to all this is that we're wrapping up the submission process [at the end of the week](https://github.com/open-organization-ambassadors/open-org-it-culture#project-timeline). What do you think is a reasonable timeline for completing two chapters? Is April 14 a possibility?

**Comment by ruhbehka** [comment]
Sounds good - yes, we can get both drafted by EOD next Fri Apr 14, or at least by the following Monday or Tuesday if some extra revisions are needed.

**Comment by semioticrobotic** [comment]
Roger that, @ruhbehka. Thanks for helping us meet our goals.

**Comment by semioticrobotic** [comment]
These chapters are typeset and in the page proofs. Thanks for the great contributions!
