### ISSUE TITLE
Book must be proofread before launch

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-it-culture#29]
It's time to proofread the book.

If you'd like to help (we sure would appreciate it!), look at the annotated table of contents below to determine which chapter you'd like to review. First, download [a set of page proofs](https://github.com/open-organization-ambassadors/open-org-it-culture/blob/master/open_org_it_culture_page_proofs.pdf). Carefully read the chapter you've selected, then leave your keen catches and edits for your chosen chapter in the comments for this issue. I'll update this issue to reflect our progress as we go along.

## Front Matter

* ~~"Preface" by Bryan Behrenshausen—**csimonse proofing**~~
* ~~"Introduction: The Open Organization comes to IT" by Mike Kelly—**csimonse proofing**~~

## Part 1: Principles

* ~~"Introduction" by Mike Walker—**chris-short proofing**~~
* ~~"What's an IT culture, anyway?" by Jono Bacon—**csimonse proofing**~~
* ~~"Organizational learning: A new perspective on DevOps" by Gene Kim—**mburke5678 proofing**~~
* ~~"Innovation requires new approaches to feedback and failure" by Jim Whitehurst—**leswilliams44 proofing**~~
* ~~"Transparency, failure, and other things I've learned to enjoy" by Nick Hall—**csimonse proofing**~~
* ~~"Why a Buffer developer open sourced his code" by Jordan Morgan—**csimonse proofing**~~
* ~~"A user's guide to failing faster" by Gordon Haff—**semioticrobotic proofing**~~
* ~~"Changing the way we think of change" by Matt Micene—**chris-short proofing**~~
* ~~"Five laws every aspiring DevOps engineer should know" by Chris Short—**leswilliams44 proofing**~~
* ~~"Why you should build a team of boundary spanners" by DeLisa Alexander—**csimonse proofing**~~
* ~~"A new approach to operations" by Chrissy Linzy—**leswilliams44 proofing**~~
* ~~"How new communication technologies are affecting peer-to-peer engagement" by Ron McFarland—**semioticrobotic proofing**~~
* ~~"What engineers and marketers can learn from each other" by Jackie Yeaney—**mburke5678 proofing**~~

## Part 2: Practices

* ~~"Introduction" by Jason Yee—**chris-short proofing**~~
* ~~"How to strengthen your agile heartbeat with powerful retrospectives" by Matt Thompson—**jmcknz proofing**~~
* ~~"The benefits of tracking issues publicly" by Chad Whitacre—**semioticrobotic proofing**~~
* ~~"Three essential skills for fostering productive debate" by Rebecca Fernandez—**jmcknz proofing**~~
* ~~"Mastering feedback loops" by Jimmy Sjölund—**jmcknz proofing**~~
* ~~"What to do when your open team has imposter syndrome" by Laura Hilliger—**semioticrobotic proofing**~~
* ~~"When innovation trumps process" by Allison Matlack—**semioticrobotic proofing**~~
* ~~"Better IT culture via the Socratic method" by Lauri Apple—**csimonse proofing**~~
* ~~"Forming and onboarding an agile team" by Jen Krieger and Hina Popal—**jmcknz proofing**~~
* ~~"A formula for running an accountable IT organization" by Stephen Gold—**semioticrobotic proofing**~~
* ~~"Institutionalizing experimentation with impact mapping" by Justin Holmes—**semioticrobotic proofing**~~
* ~~"Assuming positive intent when working across teams" by Jonas Rosland—**semioticrobotic proofing**~~

**Comment by chris-short** [comment]
Do you want to assign chapters to volunteers or do more self-service?

**Comment by semioticrobotic** [comment]
Either works for me! Someone dead set on proofing a particular chapter should go right ahead and take a look. Someone willing to take on anything that needs taking can surely ask for guidance, and I'll happily offer it.

On strategy might be: If you're an author and don't trust yourself to adequately proof your own chapter, assign a friend to do it! Some redundancy won't be an issue ("many eyes," and all that).

At the moment, @chris-short, you're the first to respond, so the board is clean.

**Comment by mrry550** [comment]
@semioticrobotic - 
"A note on style - This book uses the lower-case term "agile" as a general
descriptor for various development methods that embrace flexibility
and value responsiveness, and the capitalized term "Agile"
as a proper noun naming the specific development methodology
outlined in The Agile Manifesto." 


The Agile Manifesto never outlined any specific development methods-- probably would be better to say "naming the specific development principles..."

**Comment by semioticrobotic** [comment]
Much appreciated, @mrry550! I have made the change.

**Comment by ghost** [comment]
I can help proofread.  Please assign a chapter.

**Comment by chris-short** [comment]
Please assign me a chapter as well.

**Comment by mburke5678** [comment]
Sign me up!

**Comment by leswilliams44** [comment]
I can proofread as many chapters as you want. Feel free to assign whatever you'd like for me to look at.

**Comment by semioticrobotic** [comment]
Wow, awesome! @csimonse, @chris-short, @mburke5678, @leswilliams44 now all have chapter assignments listed above (we'll focus on Part 1 at the start). Thank you _so much_ for your invaluable help.

**Comment by mburke5678** [comment]
@semioticrobotic I don't see see my name assigned. Or am I looking in the wrong place?? Just don't want to step on anyone's work.

**Comment by ghost** [comment]
@mburke5678 refresh the page, you'll see it above!

**Comment by ghost** [comment]
@mburke5678 you are correct, Michael, others were assigned, I do not see your assignment.

**Comment by ghost** [comment]
I annotated my proofreader notes in the attached file. 
[open_org_it_culture_page_proofs-csimonse proofreader notes1.pdf](https://github.com/open-organization-ambassadors/open-org-it-culture/files/988010/open_org_it_culture_page_proofs-csimonse.proofreader.notes1.pdf)

**Comment by semioticrobotic** [comment]
Sorry about that, @mburke5678! Must have been a sloppy copy/paste on my part. I've assigned you a chapter. Again: Thank you.

**Comment by semioticrobotic** [comment]
Really great, @csimonse. Thanks for such a close and helpful reading! I've incorporated the changes (well, all but one: I kept "Joe and Josephine," because that's so quintessentially Jono that it needed to remain!).

**Comment by ghost** [comment]
LOL!  Well, I stumbled over it, but that's okay.  It's his voice:)

**Comment by ghost** [comment]
@semioticrobotic I just caught another one that I missed the first time - on page 26, "Another element here is to re-enforce..." the word should be "reinforce".

**Comment by leswilliams44** [comment]
Bryan,

I copied the text from the "Five laws..." chapter in the .pdf file and pasted it in a Google Docs file so I could make edits as suggestions. That way, you can see what was changed. I hope this is okay.

Here is the shareable link: 
https://drive.google.com/open?id=1pFDFQo3oqFfkhwHf_p3-zHL22wrCZMDE8cN9Ko9yrUw

Les

**Comment by chris-short** [comment]
"Changing the way we think of change" by Matt Micene

Page 67: That's how things like Taylorism **and and** Sloanianism get solidified and come to appear immovable.

Page 71: even while holding to the iron silo structures of management
I feel like the word **on** should appear after holding but I could be wrong

**Comment by semioticrobotic** [comment]
I am in your respective debts, @leswilliams44 and @chris-short. Thank you very much.

**Comment by chris-short** [comment]
Other way around, thanks for the opportunity to help in this project.

**Comment by leswilliams44** [comment]
@semioticrobotic, glad to help and learn something new at the same time. win-win

**Comment by semioticrobotic** [comment]
You bet, @leswilliams44. I see you have one more chapter assigned to you. I have two. Anyone else want another?

**Comment by leswilliams44** [comment]
@semioticrobotic, I should be through with my second chapter in an hour or so. I'll be glad to take another one, if no one objects.

**Comment by semioticrobotic** [comment]
There is no rush at all, @leswilliams44. I'm just trying to keep myself organized over here. I'll gladly assign you another chapter, too (and I'll make it a shorter one this time!).

**Comment by leswilliams44** [comment]
@semioticrobotic, The length of the articles has been fine. At my last job, I edited 27 manuals ranging from 100 pages to 1200 pages. These chapters are actually fun for me.

**Comment by leswilliams44** [comment]
@semioticrobotic, Here are my edits for the "A new approach to operations" chapter.

https://drive.google.com/open?id=1ZVSmkE5mbK7kuWOb0K6yMvPlzxVagfN87rIYcmi8LL4

**Comment by ghost** [comment]
I can proofread another chapter today. Will start on "Transparency, failure, and other things I've learned to enjoy" by Nick Hall

**Comment by semioticrobotic** [comment]
So helpful. Thanks, @leswilliams44.

**Comment by leswilliams44** [comment]
glad to help

**Comment by ghost** [comment]
Attached has my notes for the chapter by Nick Hall.  I'll start on the next chapter that is not assigned, which appears to be "Why a Buffer developer open sourced his code" by Jordan Morgan.

[Transparency failure pp39-49 proofreader notes from csimonse.pdf](https://github.com/open-organization-ambassadors/open-org-it-culture/files/993802/Transparency.failure.pp39-49.proofreader.notes.from.csimonse.pdf)

**Comment by semioticrobotic** [comment]
Thank you so much, @csimonse.

**Comment by ghost** [comment]
Here are my notes for the chapter by Jordan Morgan, pages 50-57.
[open_org_it_culture_page_proofs-csimonse proofreader notes -pp50-57.pdf](https://github.com/open-organization-ambassadors/open-org-it-culture/files/993969/open_org_it_culture_page_proofs-csimonse.proofreader.notes.-pp50-57.pdf)

**Comment by semioticrobotic** [comment]
Got it, @csimonse! Especially appreciate your notes about the proper footnote placement. I've gone through the entire manuscript and standardized that.

**Comment by ghost** [comment]
I'll take "Why you should build a team of boundary spanners" by DeLisa Alexander

**Comment by mburke5678** [comment]
Edits to "Organizational learning: A new perspective on DevOps". Sorry it took so long
[open_org_it_culture_page_proofs_mib_edit.pdf](https://github.com/open-organization-ambassadors/open-org-it-culture/files/994359/open_org_it_culture_page_proofs_mib_edit.pdf)

https://dochub.com/michaelburke4e3b0159/XmJjoM/open_org_it_culture_page_proofs_mib_edit

**Comment by mburke5678** [comment]
I can do ""What engineers and marketers can learn from each other"

**Comment by semioticrobotic** [comment]
You folks really rock. I'm so grateful.

**Comment by ghost** [comment]
@semioticrobotic I finished proofreading the chapter pages 79-84, "Why you should build a team of boundary spanners" by DeLisa Alexander.  There is only one correction necessary, it is on the last paragraph on page 81, "If you project teams are already cross-functional," ... should be "If your" - add an 'r' to 'you'.

I can start on the Part II Introduction by Jason Yee today!

**Comment by semioticrobotic** [comment]
Roger that, @csimonse! I've made the change.

Unfortunately, @jyee introduction is not yet finished, but should be wrapped up by the end of the weekend. If you have spare time for proofing right now, I'd recommend taking a crack at the book's preface and introduction (just be sure you're working with updated proofs, because I pushed changes to those sections both yesterday and today!).

**Comment by ghost** [comment]
Got it @semioticrobotic - so where do I find the updated proofs - same link at the top?

**Comment by semioticrobotic** [comment]
@csimonse Yes. That link _should_ always give you the most recent set of proofs.

**Comment by leswilliams44** [comment]
@semioticrobotic, Here's my edits and proofs for Jim W's article.
https://drive.google.com/open?id=17028A7_gAiUkBEEwbePldA_RcmC1X140Eik9YgPJhjM

**Comment by semioticrobotic** [comment]
Noted and logged, @leswilliams44. Great catches. Thank you.

**Comment by mburke5678** [comment]
A few nits in the engineers and marketers chapter.
See: https://dochub.com/michaelburke4e3b0159/pb3P9j/open_org_it_culture_page_proofs_mib_edit_engineer_and_marketer

**Comment by semioticrobotic** [comment]
Thanks, @mburke5678. I can't access your suggestions. Can you use the PDF link, as you did in your previous submission?

**Comment by mburke5678** [comment]
@semioticrobotic 
[open_org_it_culture_page_proofs_mib_edit_engineer_and_marketer.pdf](https://github.com/open-organization-ambassadors/open-org-it-culture/files/1002423/open_org_it_culture_page_proofs_mib_edit_engineer_and_marketer.pdf)

**Comment by ghost** [comment]
@semioticrobotic I proofread the Introduction by Mike Kelly and it is perfect as is.  I cannot proofread the Intro by Mike Walker because it is in a foreign language.  :)

**Comment by semioticrobotic** [comment]
Thanks, @mburke5678! I got 'em now. Odd about the character spacing in and around the footnotes. I am going to look into that further and hope it's not something going on book-wide. Much appreciated.

**Comment by semioticrobotic** [comment]
Ha! No sweat, @csimonse! Mike Walker's introduction is coming in soon. Glad Mike Kelly's checks out! Anything amiss in my preface?

**Comment by ghost** [comment]
A couple of minor notes on the Preface, 
[open_org_it_culture_page_proofs-Preface-proofreader-notes-csimonse-5-15-17.pdf](https://github.com/open-organization-ambassadors/open-org-it-culture/files/1002640/open_org_it_culture_page_proofs-Preface-proofreader-notes-csimonse-5-15-17.pdf)

**Comment by semioticrobotic** [comment]
Thanks, @csimonse. I see your highlighted passages, and I see blocks where comments _should_ be, but I do not see your comments.

**Comment by ghost** [comment]
@semioticrobotic in the Preface, simply, I think there is a word or something missing from this phrase "an archiecture for ensuring both the principles and the practices of openness work..." 

Second was a suggestion that you do something to avoid hyphenating Opensource.-
com

**Comment by semioticrobotic** [comment]
Thanks, @csimonse. I'll look into them both. Appreciate it!

**Comment by semioticrobotic** [comment]
Mike Walker's "Introduction to Part 1" came in today. I've proofed and typeset it. Would someone else mind read it over and double-checking it for me?

**Comment by jmcknz** [comment]
I can proof Matt Thompson's "retrospectives" chapter. Feel free to assign others if needed.

**Comment by jmcknz** [comment]
Proofread Thompson (pp. 111-116). 
[open_org_it_culture_page_proofs_pp111-116.pdf](https://github.com/open-organization-ambassadors/open-org-it-culture/files/1008990/open_org_it_culture_page_proofs_pp111-116.pdf)

**Comment by jmcknz** [comment]
Can proofread a couple more chapters today: Fernandez and Sjolund.

**Comment by semioticrobotic** [comment]
Thanks, @jmcknz. Just incorporated your suggestions on the Thompson chapter, which were excellent. Great catches.

**Comment by ghost** [comment]
@semioticrobotic I can proofread more today.  I'll take "Better IT culture via the Socratic method" by Lauri Apple
Edit/add:  attached are my notes
[laura-apple-chapter-pp147-157-csimonse-proofreader-notes.pdf](https://github.com/open-organization-ambassadors/open-org-it-culture/files/1012613/laura-apple-chapter-pp147-157-csimonse-proofreader-notes.pdf)

**Comment by semioticrobotic** [comment]
Many thanks, @csimonse. I'll be able to get these into today's code push!

**Comment by semioticrobotic** [comment]
Does anyone have the time and/or bandwidth to read through the section introductions by Mike Walker and Jason Yee?

**Comment by chris-short** [comment]
I probably should be working on my talk this week but I can.

**Comment by semioticrobotic** [comment]
You should most definitely prioritize the talk, @chris-short, but if it's any consolation: The introductions are rather short.

**Comment by chris-short** [comment]
I'll proofread now.

**Comment by chris-short** [comment]
In the Mike Walker intro I would remove the comma after group:

>  If it came from another group, or was abandoned entirely, it still wouldn't stop us from achieving our mission.

Jason Yee's intro looks good.

**Comment by semioticrobotic** [comment]
Thanks, @chris-short. Appreciate the second set of eyes on those.

**Comment by jmcknz** [comment]
@semioticrobotic My proofreading comments on Jimmy Sjolund's "Mastering feedback loops." 
[open_org_it_culture_proofread_pp128-134.pdf](https://github.com/open-organization-ambassadors/open-org-it-culture/files/1023022/open_org_it_culture_proofread_pp128-134.pdf)

**Comment by semioticrobotic** [comment]
Great catches, @jmcknz. I just incorporated all the changes. Much obliged.

**Comment by semioticrobotic** [comment]
General update on this issue: We'll need to cement all book chapters by Friday, May 26. I plan to read most of the unproofed chapters by then. Anyone wishing to do one more should speak now or forever hold your typos.

**Comment by jmcknz** [comment]
And just a couple of very minor suggestions for Rebecca Fernandez's "Three essential skills...": 
[open_org_it_culture_proofread_pp123-127.pdf](https://github.com/open-organization-ambassadors/open-org-it-culture/files/1023091/open_org_it_culture_proofread_pp123-127.pdf)

**Comment by semioticrobotic** [comment]
Got 'em! Thanks, @jmcknz.

**Comment by jmcknz** [comment]
I can do one more: Krieger/Popal.

**Comment by jmcknz** [comment]
@semioticrobotic Proofreading comments for Krieger/Popal: 
[open_org_it_culture_pp158-167.pdf](https://github.com/open-organization-ambassadors/open-org-it-culture/files/1026135/open_org_it_culture_pp158-167.pdf)

**Comment by semioticrobotic** [comment]
Got it, @jmcknz. Nice catches. I've just pushed today's set of galley proofs, which includes your edits.

**Comment by semioticrobotic** [comment]
Well, everyone, we did it.

I really can't thank you enough. If you helped proofread the book and have not yet [registered to receive your copies](https://docs.google.com/forms/d/e/1FAIpQLSd3B8dwOVWWKADmmHkZQsgqkSeOQmdf0zEvYjr4TY5KlUI9Cw/viewform?usp=sf_link), please don't forget to do so!
