### ISSUE TITLE
Write a chapter on agile communication and mastering feedback loops

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-it-culture#3]
We'll need to compose a chapter on agile communication cadences.

(See the [current table of contents](https://github.com/open-organization-ambassadors/open-org-it-culture/blob/master/open_org_it_culture_toc.md).)

**Comment by jimmysjolund** [comment]
I'm quite interested in agile and communication but I'm not sure what you are referring to or thinking of here, could you elaborate?

**Comment by semioticrobotic** [comment]
Great question, @jimmysjolund. We've learned that this idea would be better expressed as "write a chapter on effectively harnessing feedback loops." Essentially, we think the book needs a chapter that explores the intricacies of feedback practices—the role feedback plays in open IT organizations, the changing nature of feedback in agile environments, strategies for giving/receiving feedback effectively, cultural approaches to feedback, and so forth.

You interested?

**Comment by jimmysjolund** [comment]
Interested yes, but not sure about my take on the subject. What are the expectations on a chapter in length and depth?

**Comment by semioticrobotic** [comment]
We're seeking chapters that are roughly 800 to 1,000 words in length (can be longer if need be) on each topic. Some authors have pitched deep-dive-style chapters that explore single issues in greater depth. Others are taking an overview/survey approach to a range of issues on a topic.

**Comment by jimmysjolund** [comment]
Sure I'd take on the topic! I'll start drafting and send it over as soon as I can.

**Comment by semioticrobotic** [comment]
@jimmysjolund is my hero. You got it!

**Comment by jhibbets** [comment]
@semioticrobotic is this also "Mastering feedback loops" ??

**Comment by semioticrobotic** [comment]
@jhibbets Yes; I need to update the issue title.

**Comment by jimmysjolund** [comment]
When looking at the time schedule, I wonder if you are expecting me to send something in before April 7?

March 28—Finalized table of content and author roster published
March 30—Final book outline complete
April 7—All chapter drafts due to Opensource.com team

**Comment by semioticrobotic** [comment]
Our goal is to start receiving chapters by April 7 so we can begin collaborative editing with writers. If you need an extra day or two, then that's certainly fine!

**Comment by jimmysjolund** [comment]
Should I upload my writing here or send it through email (as before)?

**Comment by semioticrobotic** [comment]
Either is fine, @jimmysjolund, and whatever is most convenient for you is best for us. Most folks have been emailing or sharing a link to a collaborative editor, since that seems to speed up the potential pace of revisions.

**Comment by semioticrobotic** [comment]
Chapter from @jimmysjolund is now finished and available for review in the galley proofs.
