### ISSUE TITLE
Open Org book series landing page

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/open-org-it-culture#33]
@semioticrobotic - what do you think about re-organizing the Open Org menu and created a landing page for the open source book series, then relocating the 3 (soon to be 4) book landing pages to live under that instead of resource?

**Comment by semioticrobotic** [comment]
Yes, @jhibbets, I think this is a good idea. Let's discuss before the launch. We welcome input from any lurking, expert UX folks, too!

**Comment by semioticrobotic** [comment]
This is [now live](https://opensource.com/open-organization/resources/book-series). Some killer lead artwork coming soon!
