### ISSUE TITLE
Update to graphic

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/open-org-it-culture#34]
@semioticrobotic I just noticed that in this lead image:
https://opensource.com/sites/default/files/images/openorg_itculturechage.png

The "I" in IT in the main ASCII text is missing the bottom. It almost looks like two T's. Compared to the I in GUIDE, the I in IT is wrong.

**Comment by semioticrobotic** [comment]
Interesting. Nice catch. I will alert the designers right away.

**Comment by semioticrobotic** [comment]
An updated promo image is [now available](https://github.com/open-organization-ambassadors/open-org-it-culture/blob/master/openorg_ITculturechage-promo-520x292.png).
