### ISSUE TITLE
Test book download process

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-it-culture#35]
The book's official landing page is [now live](https://opensource.com/open-organization/resources/culture-change) and ready for testing. If you'd like, please do help us test the book download experience by visiting the page and acquiring your PDF copy of the book. Yes—that is a real, live copy of v1.0 you'll receive by doing so!

If you encounter errors or have suggestions for enhancing the user experience, then please let us know as part of this issue and we'll work quickly to rectify nagging issues. Otherwise, enjoy your copy of the book this weekend!

**Comment by jonasrosland** [comment]
Works like a charm! The Captcha is a bit strange looking but otherwise no issues. Well done!

**Comment by semioticrobotic** [comment]
Thanks for helping, @jonasrosland! Enjoy the book this weekend!

**Comment by semioticrobotic** [comment]
I've been receiving positive email feedback throughout the holiday weekend, all of which indicates that the download process is free of kinks and running smoothly.
