### ISSUE TITLE
EPUB Version?

### ISSUE THREAD

**Issue by cwawak** [open-organization-ambassadors/open-org-it-culture#36]
I'd love to be able to read this on an e-reader. Is it possible to build an EPUB version of the book? Thank you!

**Comment by semioticrobotic** [comment]
Thanks, @cwawak! Building an ePub version is most definitely possible using the ODT source from this repository. Community members have done it with the previous volumes, and we sure hope they will do it again with this one! Pull requests welcome!

**Comment by jhibbets** [comment]
Although creating an ePub isn't a priority for our team at this time, as @semioticrobotic mentioned, many time our community members have stepped up to do this and submitted a pull request. The same for translated versions. 

We have some excellent documentation via an article that Bryan wrote if anyone wants to use this to create an ePub version: 
https://opensource.com/life/13/8/how-create-ebook-open-source-way

**Comment by boblmartens** [comment]
I seconded this above, but EPUB would be really great for the future.

**Comment by chris-short** [comment]
I'll take a stab at it during my lunch break.

**Comment by chris-short** [comment]
Oof... This is a bridge too far for me with the time I have.

**Comment by semioticrobotic** [comment]
No sweat, @chris-short! Eat your lunch!

**Comment by boblmartens** [comment]
@chris-short I tried my hand at it before posting but the output was ... less than ideal ...

**Comment by semioticrobotic** [comment]
Yes, @romainsc is the person we [need to ping](https://github.com/open-organization-ambassadors/open-org-leaders-manual/pull/1).

**Comment by chris-short** [comment]
This is the image I wanted to use for the front.
![theopenorg_guidetoitculturechange_1_0_cover_final_front](https://cloud.githubusercontent.com/assets/1393145/26758618/8dcdd42e-48b1-11e7-865b-4e294f35bcd1.png)

**Comment by romainsc** [comment]
Hi, I proposed two pull requests:

1. with the official cover (face and back)
2. with the @chris-short  one.

Best Regards,

**Comment by semioticrobotic** [comment]
Coming to our aid once again is @romainsc! Thanks to this commit, an ePub version is now officially available in the project repository.
