### ISSUE TITLE
Send out template to post to LinkeIn Publications

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/open-org-it-culture#37]
Need to draft an email and instructions for authors who would like to update their LinkedIn profile to list Guide to IT Culture as a publication for their portfolio.

**Comment by chris-short** [comment]
I've put it under Publications: https://www.linkedin.com/in/christopherbshort/

**Comment by jhibbets** [comment]
*How to add a publication to your Linked In profile*

1) Log in to your Linked In account.
2) Navigate to the "me" option in the top navigation and select View profile.
3) Scroll down (perhaps way down depending on your profile) and you'll see a section called *Accomplishments* below Featured Skills & Endorsements and Recommendations. 
4) Select the plus sign to the right of the Accomplishments header and select Publication.
5) Complete with the following details:
- Title: The Open Organization Guide to IT Culture Change
- Publication/Publisher: Opensource.com
- Publication Date: June 2, 2017
- Publication URL: https://opensource.com/it-culture
- Description: The Open Organization Guide to IT Culture Change consists of more than 25 chapters from writers, practitioners, industry leaders, and notable technologists. The book explains how open principles are reshaping IT organizations today and offers practical advice for leaders seeking to catalyze powerful and lasting cultural changes in their IT organizations.
- Share profile change (optional) - Slide to Yes if you want to share
6) Save. Thank you!
