### ISSUE TITLE
Write a chapter on positive intent

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-it-culture#4]
We'll need to compose a chapter on assuming positive intent when working across team boundaries.

(See the [current table of contents](https://github.com/open-organization-ambassadors/open-org-it-culture/blob/master/open_org_it_culture_toc.md).)

**Comment by jonasrosland** [comment]
Hi!

I would love to sign up for this chapter as it fits well into what I do on a day to day basis.
I've sent an email to @jhibbets, looking forward to working with you all on this :)

**Comment by semioticrobotic** [comment]
Confirmed, @jonasrosland, that you are now the author of this chapter. Thanks so much for volunteering. You're welcome to use this space or the private email conversation we've begun as channels for brainstorming, planning, drafting, etc.

**Comment by semioticrobotic** [comment]
How's your second draft coming along, @jonasrosland? Any update you can share?

**Comment by semioticrobotic** [comment]
@jonasrosland wrote an excellent chapter that I'm slowly getting into page proofs. Look for it in the very near future.
