### ISSUE TITLE
Possible repeated word in "What's an IT culture, anyway?"

### ISSUE THREAD

**Issue by mpkono** [open-organization-ambassadors/open-org-it-culture#41]
I'm still fairly new to GitHub and I've never contributed to anything open source before, so I do not know if this is appropriate or the correct way to go about this. 

In the opening paragraph of Jono Bacon's "What's an IT culture, anyway?" piece, the word "exactly" looks like it may have been inadvertently repeated.

_"Sure, reams of social science research explore **exactly** what **exactly** "culture" is"..._

Again, apologies if this is not how to do this, but I'm trying to take my first steps into this open culture. If I'm "doing it wrong" and someone can point me to the right way, I'm happy to learn.

**Comment by semioticrobotic** [comment]
Thanks so much, @mpkono, for your time and effort submitting this issue. You've done everything here in precisely the correct and expect way, and we're very appreciative! I've just made the change and will push an update to the book momentarily, so I'm closing this issue. Welcome to the community, @mpkono!
